# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('current_waiver', models.BooleanField()),
                ('ec_first_name', models.CharField(max_length=100)),
                ('ec_last_name', models.CharField(max_length=100)),
                ('ec_phone_number', models.BigIntegerField()),
                ('uuID', models.UUIDField(editable=False)),
            ],
        ),
    ]
