# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_delete_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='222', max_length=100),
        ),
    ]
