# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuID',
        ),
    ]
