# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Identified', 'NotIdentify')], default='Not Identified', max_length=100),
        ),
    ]
