# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('smid', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Tool')),
            ],
        ),
    ]
