# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PunchIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.BigIntegerField()),
                ('smid', models.BigIntegerField()),
                ('time', models.DateTimeField(verbose_name='punch in time')),
            ],
        ),
        migrations.CreateModel(
            name='PunchOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smid', models.BigIntegerField()),
                ('time', models.DateTimeField(verbose_name='punch out time')),
            ],
        ),
    ]
