# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smid', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_pkey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rfid', models.BigIntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Please use the format 9999999999. Max 10 numbers.', regex='^\\+?1?\\d{9,11}$')])),
                ('sex', models.CharField(choices=[('NS', 'Rather not say'), ('ML', 'Male'), ('FL', 'Female'), ('NB', 'Non-Binay'), ('TS', 'Transgender')], default='NS', max_length=64)),
                ('current_waiver', models.BooleanField(default=False)),
                ('ec_first_name', models.CharField(blank=True, max_length=64)),
                ('ec_last_name', models.CharField(blank=True, max_length=64)),
                ('ec_phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Please use the format 9999999999. Max 10 numbers.', regex='^\\+?1?\\d{9,11}$')])),
                ('ec_relation', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='SpecialUser',
            fields=[
                ('user_pkey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeIn', models.DateTimeField(auto_now_add=True)),
                ('TimeOut', models.DateTimeField()),
                ('smid_pkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aumwi.ModuleList')),
                ('user_pkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='authuser',
            name='smid_pkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aumwi.ModuleList'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='user_pkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
