# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0002_auto_20170327_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smid', models.BigIntegerField()),
                ('time_in', models.DateTimeField(verbose_name='punch in time')),
                ('time_out', models.DateTimeField(blank=True, verbose_name='punch out time')),
                ('rfid', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PunchIn',
        ),
        migrations.DeleteModel(
            name='PunchOut',
        ),
    ]
